=== GNOME/gdm/gui/greeter/greeter.dtd
<!-- dtd for greeter -->
<!ENTITY % colorattrs "file CDATA #IMPLIED
	color CDATA #IMPLIED
	font CDATA #IMPLIED
	tint CDATA #IMPLIED">
<!ELEMENT greeter (item+)>
<!ELEMENT item (pos | normal? | active? | prelight? | children? | show? | text? | fixed? | box?|border?)*>
<!ELEMENT children (item+)>
<!ELEMENT pos EMPTY>
<!ELEMENT show EMPTY>
<!ELEMENT text (#PCDATA)>
<!ELEMENT normal EMPTY>
<!ELEMENT active EMPTY>
<!ELEMENT prelight EMPTY>
<!ELEMENT stock EMPTY>
<!ELEMENT fixed (item+)>
<!ELEMENT box (item+)>
<!-- additional elements-->
<!ELEMENT border EMPTY>

<!ATTLIST item
	type (rect | entry | pixmap | label | svg | rect | list) #REQUIRED
	id (user-pw-entry | caps-lock-warning | clock | pam-error | pam-message | pam-prompt | pam-warning | timed-label | timed-rect | language_button | disconnect_button | reboot_button | halt_button | session_button | suspend_button | system_button | config_button | chooser_button | userlist) #IMPLIED
	button (true | false) #IMPLIED
>
<!ATTLIST pos
	x CDATA #IMPLIED
	y CDATA #IMPLIED
	anchor CDATA "c"
	width CDATA #IMPLIED
	height CDATA #IMPLIED
>
<!ATTLIST normal
	%colorattrs; 
	alpha CDATA #IMPLIED
>
<!ATTLIST active
	%colorattrs; 
	alpha CDATA #IMPLIED
>
<!ATTLIST prelight
	%colorattrs; 
	file CDATA #IMPLIED
>
<!ATTLIST stock
	type (language | session | system | disconnect | quit | caps-lock-warning | timed-label | welcome-label | username-label | config | chooser) #REQUIRED
>
<!ATTLIST box
	orientation (horizontal | vertical) "horizontal"
	spacing CDATA #IMPLIED
	xpadding CDATA #IMPLIED
	ypadding CDATA #IMPLIED
	min-width CDATA #IMPLIED
	min-height CDATA #IMPLIED
>
<!-- console,console-fixed,console-flexi,remote-flexi,flexi,remote-->
<!ATTLIST show
	modes CDATA #IMPLIED
	type (config | chooser | system | halt | reboot | suspend | timed) #IMPLIED
>
<!ATTLIST text
	xml:lang CDATA #IMPLIED
>

<!-- <border red="0" green="0" blue="10" alpha="255"/>-->

<!ATTLIST border
	red CDATA #IMPLIED
	green CDATA #IMPLIED
	blue CDATA #IMPLIED
	alpha CDATA #IMPLIED
>

=== GNOME/gdm/gui/greeter/themes/circles/circles.xml
<?xml version="1.0"?>
<!DOCTYPE greeter SYSTEM "greeter.dtd">
<greeter>
  <item type="svg">
    <normal file="background.svg"/>
    <pos x="0" y="0" width="100%" height="-75"/>
  </item>
  <item type="rect">
    <normal color="#000000"/>
    <pos x="0" y="-75" width="100%" height="75"/>
    <fixed>
      <item type="rect">
        <normal color="#ffffff"/>
        <pos x="0" y="4" width="100%" height="100%"/>
        <box orientation="horizontal" spacing="10" xpadding="10">
          <item type="rect" id="language_button" button="true">
            <normal color="#ffffff"/>
	    <pos y="50%" anchor="w" width="box" height="box"/>
            <box orientation="horizontal" spacing="10" xpadding="10">
	      <item type="pixmap">
	        <normal file="options.png" tint="#dddddd"/>
	        <prelight file="options.png"/>
	        <active file="options.png" tint="#ff0000"/>
	        <pos y="50%" anchor="w"/>
	      </item>
	      <item type="label">
	        <normal color="#000000" font="Sans 14"/>
		<prelight color="#666666" font="Sans 14"/>
		<active color="#ff0000" font="Sans 14"/>
	        <pos y="50%" anchor="w"/>
	        <text>Option</text>
	      </item>
            </box>
          </item>
          <item type="rect" id="session_button" button="true">
            <normal color="#ffffff"/>
	    <pos y="50%" anchor="w" width="box" height="box"/>
            <box orientation="horizontal" spacing="10" xpadding="10">
	      <item type="pixmap">
	        <normal file="help.png" tint="#dddddd"/>
	        <prelight file="help.png"/>
	        <active file="help.png" tint="#ff0000"/>
	        <pos y="50%" anchor="w"/>
	      </item>
	      <item type="label">
	        <normal color="#000000" font="Sans 14"/>
		<prelight color="#666666" font="Sans 14"/>
		<active color="#ff0000" font="Sans 14"/>
	        <pos y="50%" anchor="w"/>
	        <text>Session</text>
	      </item>
            </box>
          </item>
          <item type="rect" id="system_button" button="true">
            <normal color="#ffffff"/>
	    <show modes="console" type="system"/>
	    <pos y="50%" anchor="w" width="box" height="box"/>
            <box orientation="horizontal" spacing="10" xpadding="10">
	      <item type="pixmap">
	        <normal file="options.png" tint="#dddddd"/>
	        <prelight file="options.png"/>
	        <active file="options.png" tint="#ff0000"/>
	        <pos y="50%" anchor="w"/>
	      </item>
	      <item type="label">
	        <normal color="#000000" font="Sans 14"/>
		<prelight color="#666666" font="Sans 14"/>
		<active color="#ff0000" font="Sans 14"/>
	        <pos y="50%" anchor="w"/>
	        <text>System</text>
	      </item>
            </box>
          </item>
          <item type="rect" id="disconnect_button" button="true">
            <normal color="#ffffff"/>
	    <show modes="flexi,remote"/>
	    <pos y="50%" anchor="w" width="box" height="box"/>
            <box orientation="horizontal" spacing="10" xpadding="10">
	      <item type="pixmap">
	        <normal file="options.png" tint="#dddddd"/>
	        <prelight file="options.png"/>
	        <active file="options.png" tint="#ff0000"/>
	        <pos y="50%" anchor="w"/>
	      </item>
	      <item type="label">
	        <normal color="#000000" font="Sans 14"/>
		<prelight color="#666666" font="Sans 14"/>
		<active color="#ff0000" font="Sans 14"/>
	        <pos y="50%" anchor="w"/>
	        <text>Disconnect</text>
	        <show modes="remote"/>
	      </item>
	      <item type="label">
	        <normal color="#000000" font="Sans 14"/>
		<prelight color="#666666" font="Sans 14"/>
		<active color="#ff0000" font="Sans 14"/>
	        <pos y="50%" anchor="w"/>
	        <text>Quit</text>
	        <show modes="flexi"/>
	      </item>
            </box>
          </item>
        </box>
      </item>
    </fixed>
  </item>
  <item type="pixmap">
    <normal file="flower.png"/>
    <pos x="100%" y="100%" anchor="se"/>
  </item>
  <item type="label" id="clock">
    <normal color="#000000" font="Sans 16"/>
    <pos x="-20" y="-37" anchor="e"/>
    <text>%c</text>
  </item>

  <item type="rect" id="caps-lock-warning">
    <normal color="#FFFFFF" alpha="0.5"/>
    <pos anchor="c" x="50%" y="75%" width="40%" height="5%"/>
    <fixed>
      <item type="label">
        <normal color="#000000" font="Sans 14"/>
        <pos x="66" y="50%" anchor="w"/>
        <text>You've got capslock on!</text>
      </item>
    </fixed>
  </item>
  <item type="rect">
    <normal color="#FFFFFF" alpha="0.5"/>
    <pos anchor="c" x="50%" y="50%" width="box" height="box"/>
    <box orientation="vertical" min-width="300" xpadding="30" ypadding="30" spacing="10">
      <item type="label">
        <pos anchor="n" x="50%"/>
        <normal color="#000000" font="Sans 18"/>
	<text>Welcome to %h</text>
	<text lang="sv">VÃ¤lkommen till %h</text>
      </item>
      <item type="label" id="pam-prompt">
        <pos anchor="nw" x="10%"/>
        <normal color="#000000" font="Sans 16"/>
	<text>Username:</text>
      </item>
      <item type="rect">
	<normal color="#000000"/>
        <pos anchor="n" x="50%" height="24" width="80%"/>
	<fixed>
	  <item type="entry" id="user-pw-entry">
            <pos anchor="nw" x="1" y="1" height="-2" width="-2"/>
	  </item>
	</fixed>
      </item>
      <item type="label" id="pam-message">
        <pos anchor="n" x="50%"/>
        <normal color="#000000" font="Sans 16"/>
	<text></text>
      </item>
    </box>
    <fixed>
      <item type="label" id="pam-error">
        <pos anchor="n" x="50%" y="110%"/>
        <normal color="#000000" font="Sans 16"/>
        <text></text>
      </item>
    </fixed>
  </item>
</greeter>
